exclude: '^src/libs'
fail_fast: true
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    - id: flake8
      args: ['--max-line-length=90', '--ignore=E203,E121,E123,E126,E226,E24,E704,W503,W504']
-   repo: local
    hooks:
    - id: nosetests
      name: nosetests
      entry: bash -ec 'nosetests --with-coverage --cover-package=src/exploration/core --cover-package=src/exploration/loaders'
      language: system
      files: \.py$
-   repo: local
    hooks:
    - id: coverage
      name: coverage
      entry: bash -ec 'coverage report --fail-under=50'
      language: system
      files: \.py$
