version: 2
jobs:
  build:
    docker:
      - image: ysebiat/pyspark231:python35

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            eval "$(pyenv init -)"
            pyenv local 3.5.3
            pip install -r requirements.txt

      - save_cache:
          paths:
            - /root/.pyenv/versions/3.5.3/lib/python3.5/site-packages
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            eval "$(pyenv init -)"
            pyenv local 3.5.3
            cat /dev/null | python -m nose --with-coverage --cover-package=src/exploration/core --cover-package=src/exploration/loaders --cover-package=src/exploration/flattening

      - run:
          name: Run coverage
          command: |
            eval "$(pyenv init -)"
            cat /dev/null | codecov -t 7f9c7390-37df-46bc-8d25-08edd04377d3
